/* ================= plain-language definitions ================= */
/* Each entry: the name, then what it means in everyday words. These show when a reader points at a column heading or taps a dotted word. */
const GLOSS = {
  index:["LTF Index", "One score for every team, from 0 to 100. An average team is 50, a good one is in the 60s, and the very best are near 80 or higher. It is built from results, play-by-play stats and computer ratings. Polls are not used."],
  ltf:["LTF Index", "LTF is short for Level the Field. The LTF Index is the site's own formula: résumé 20%, offense 25%, defense 25%, computer ratings 30%. Those weights came from a test on five past seasons."],
  rec:["Record", "Wins and losses. The smaller numbers next to it are the conference record."],
  lw:["Last week", "Where the team ranked a week ago, and how many spots they have moved since."],
  change:["Change", "How many spots the team moved in the national ranking since last week."],
  res:["Résumé", "What the team has earned on the field so far: who they beat, who they lost to, and by how much. The number is their national rank, so 1 is the best résumé in the country."],
  off:["Offense", "How good the offense is at moving the ball and scoring, after allowing for the defenses they have faced. The number is their national rank."],
  def:["Defense", "How good the defense is at stopping drives and keeping points off the board, after allowing for the offenses they have faced. The number is their national rank."],
  cmp:["Computer ratings", "What four well-known rating systems think of the team, averaged: SP+, FPI, SRS and Elo. They remember earlier seasons, which keeps one hot month from fooling the score. The number is the national rank."],
  form:["Last 3", "The last three games, oldest first. W is a win and L is a loss. An orange dot means the team also covered the spread that day."],
  ats:["Against the spread", "How the team has done against the betting line: times they covered, times they did not, then pushes. A 7-point favorite covers by winning by 8 or more. A win by exactly 7 is a push."],
  cover:["Cover", "A team covers when they beat the point spread. A 7-point favorite has to win by 8 or more. A 7-point underdog covers if they win outright or lose by 6 or fewer."],
  epa:["EPA per play", "How much each play helps the team score. A 15-yard gain makes the drive worth more points, and a sack makes it worth fewer. This is the average over every play."],
  sr:["Success rate", "How often a play does its job. On first down that means gaining half the yards needed. On second down it means 70% of them, and on third or fourth down all of them."],
  ppd:["Points per drive", "Points scored each time the offense gets the ball."],
  ppo:["Points per scoring opportunity", "Points scored each time a drive gets inside the other team's 40-yard line. It shows who finishes drives with touchdowns and who settles for field goals or comes away with nothing."],
  net:["Net points per scoring opportunity", "Points per scoring chance on offense, minus what the defense gives up per chance. Above zero means the team wins the battle in scoring range."],
  exp:["Explosive play rate", "How often a play goes for big yards: a run of 10 or more, or a pass of 20 or more."],
  yds:["Yards per game", "Total yards gained in a game. It counts for only a small part of the score, because yards do not always turn into points."],
  stop:["Stop rate", "How often the defense ends a drive with no points: a punt, a turnover or a turnover on downs."],
  hav:["Havoc rate", "How often the defense wrecks a play: a tackle for loss, a sack, an interception, a pass breakup or a forced fumble."],
  ru:["Rushing EPA per play", "How much each run helps the team score, on average. Shown for depth. It is not part of the score."],
  pa:["Passing EPA per play", "How much each pass play helps the team score, on average, with sacks counted. Shown for depth. It is not part of the score."],
  sdn:["Success rate, standard downs", "How often a play works when the offense is on schedule: first down, second and 7 or less, or third and 4 or less."],
  pdn:["Success rate, passing downs", "How often a play works when the offense is behind schedule and the defense expects a pass: second and 8 or more, or third and 5 or more."],
  sor:["Strength of record", "How hard this record would be to match. A 90 means a typical top-25 team would do worse than this nine times out of ten against the same schedule."],
  line:["LTF line", "How many points better LTF thinks one team is in this game, with 2.5 points added for the home team. “Alabama −7” means Alabama by 7."],
  market:["Market line", "The sportsbook point spread. “Alabama −7” means the sportsbooks favor Alabama by 7."],
  lean:["LTF Edge", "The gap between the LTF line and the market line, and the team it favors. “Maryland +13.5” means LTF rates Maryland 13.5 points better than the sportsbooks do. It is a difference of opinion, not a sure thing. In past seasons, gaps under 4 points were coin flips against the spread."],
  wc:["Win chance", "How often LTF expects the team to win this game, worked out from the LTF line."],
  conf:["Confidence", "The chance the LTF pick wins, from 1 to 99. A 50 is a coin flip. When a market line is posted, the score blends it with the LTF line, because five past seasons show that gives the most honest number."],
  gs:["Game score", "How good one performance was, on the same 0 to 100 scale as the LTF Index. It weighs the final margin against how strong the opponent is and where the game was played. 50 is an average showing."],
  ps:["Projected score", "The LTF line split around a projected total. The total comes from each team's points per drive and pace. Treat it as a rough guide. In testing it was a little worse than the market total, so the site does not make over-under picks from it."],
  po:["Playoff chance", "The share of 2,500 simulated seasons in which the team makes the 12-team playoff."],
  ct:["Conference title chance", "The share of simulated seasons in which the team wins their conference championship game."],
  bowl:["Bowl eligible", "The share of simulated seasons in which the team reaches six wins, the mark for bowl eligibility."],
  xw:["Projected wins", "The average number of regular-season wins across the simulated seasons."],
  wt:["Win totals", "The share of simulated seasons in which the team finishes the regular season with at least that many wins."],
  open:["Opening line", "Where the market line started when it was first posted. Movement since then shows which side bettors have pushed."],
  luck:["Luck", "Points per game the team has gained or lost from things that mostly do not repeat: which way fumbles bounce, how many tipped passes get picked off, and how well opposing kickers do."],
  steady:["Steadiness", "How much the team's game scores swing from week to week. A steady team plays close to the same level every time."],
  mkt:["Market rating", "What the betting market thinks of the team, worked back out of their point spreads from the last three weeks and this week. It is in points better than an average team."],
  seed:["Seed", "Where the team would be placed in the 12-team playoff. The top four seeds get a first-round bye."],
  adv:["Chance to advance", "How often the team gets through that round, worked out from the LTF line for every matchup they could face."],
  nat:["National rank", "Where the team ranks among all FBS teams, not only the group shown."],
  apr:["AP poll", "The team's rank in the Associated Press Top 25, voted on by sportswriters. It is shown for comparison only and is never part of the LTF Index."],
  ltfrank:["LTF rank", "Where the team ranks among all FBS teams by LTF Index."],
  mom:["Momentum", "How a team is trending, from minus 10 to plus 10. It blends the change in their LTF Index over three weeks, how their last two games graded against the ones before, and recent results: streaks, upsets and covers. It is shown for the story and is not part of the LTF Index, because twelve past seasons say it does not predict the next game."],
  mtrend:["LTF Index, three weeks", "How far the team's LTF Index has moved over the last three weeks. Above zero means they are rated higher now."],
  mplay:["Last two games", "The average game score of the last two games, next to the average of the games before them. A game score of 50 is an average showing."],
  mstreak:["Streak", "Wins or losses in a row coming into this week. W3 is three straight wins."],
  mats:["ATS, last 3", "Record against the spread over the last three games: covers, then misses, then pushes."],
  mups:["Upset wins", "Wins this season as an underdog of 3 points or more."],
  mout:["Outlook", "A read on where a team is headed, in points a game. Above zero means the LTF Index is probably too low on them. Below zero means results have run ahead of what tends to last. It comes from three things that marked climbers and sliders in past seasons: failing to cover the spread, a much higher rating before the season, and bad turnover luck. It fades by midseason."],
  mprog:["Since last season", "Where the team finished last season by power rating, and how many spots their LTF rank today is above or below that."],
};
